version: "3"

services:
  server:
    image: gitea/gitea:1.16.6
    container_name: gitea
    env_file:
      - .env
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:${PORTGRES_PORT}
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORTGRES_PORT}:80"
    volumes:
      - gitea-postgres:/var/lib/postgresql/data

volumes:
  gitea:
  gitea-postgres:

